## Install edgeR
# if (!requireNamespace("BiocManager", quietly = TRUE)) + install.packages("BiocManager")
# BiocManager::install("edgeR")

## Set working directory. Must contain:
## 1-Comma delimited raw counts, with columns=samples, and rows=genes
## 2-Comma delimited file with sample name in first column (matching raw counts file), situation in second column, and sex in third column (in that order)
## No column names. Only alphanumeric characters [A-z0-9] for file 2

library("edgeR")
library("gplots")
library("RColorBrewer")
library("ComplexHeatmap")
library("MASS")
library("pvclust")
library("dendextend")

path <- "/Users/oscar/Desktop/edgeR_analyses_AlanCounts"
setwd(path)

## Give name of raw count file, including the csv extension
countfile <- "sumRawCounts.csv"

## Give name of samples file, including the csv extension
samplesfile <- "samples.csv"

## Load raw counts
fercounts <-  read.csv(countfile, header=T)
fercounts <- na.omit(fercounts)
rownames(fercounts) <- fercounts[,1]
fercounts <- fercounts[,-1]

## Remove specific column (such as outliers)... CAREFUL AS ROW NEEDS TO BE REMOVED FROM SAMPLE FILE, AND ADJUSTMENTS ION OTHER COMMANDS NEED TO BE DONE
fercounts <- fercounts[, -grep("I29365", colnames(fercounts))]

## Create DGEList object with factors and groups
sampleMeta <- read.csv(samplesfile, header=T)
rownames(sampleMeta) <- sampleMeta[,1]
sample.ids <- apply(sampleMeta[,1:3], 1, paste, collapse="_")
indivs <- c()
for (i in 1:length(colnames(fercounts))) { 
	loop<-grep(colnames(fercounts[i]), sample.ids, value=T)
	indivs[[length(indivs) + 1]]<-loop 
}

situation <- gsub("^[[:alnum:]]*_", "", indivs)
situation <- gsub("_[[:alnum:]]*$", "", situation)
sex <- gsub("\\w*_", "", indivs)
Group <- factor(paste(situation, sex, sep="."))
dgList <- DGEList(counts=fercounts, group=Group)
dgList_CPM <- cpm(dgList)
dgList_logCPM <- cpm(dgList, log=T, prior.count=2)

## Add "Group" (situation x sex) column to sampleMeta
sampleMeta <- cbind(sampleMeta, Group)

## Design matrix
design <- model.matrix(~ 0 + Group)
colnames(design) <- levels(Group)

## Plot of count density (log-base2 of counts with 2 pseudocounts), before normalization
pdf(file="density_log2CPM.pdf")
# sampleColors=c("blue", "blue", "deepskyblue", "blue", "deepskyblue", "blue", "deepskyblue", "blue", "red", "red", "pink", "red", "pink", "pink", "red", "red", "pink")
sampleColors=c("blue", "blue", "deepskyblue", "blue", "deepskyblue", "blue", "deepskyblue", "blue", "red", "pink", "red", "pink", "pink", "red", "red", "pink") ## IN CASE I29365 WAS REMOVED
plot(density(cpm(dgList[,1], log=T, prior.count=2)), col=sampleColors[1], lwd=2, ylim=c(0,0.3), xlab="log2CPM + 2", main="Before TMM normalization")
for(i in 2:length(colnames(dgList$counts))) { 
	lines(density(cpm(dgList[,i], log=T, prior.count=2)), col=sampleColors[i], lwd=2)
}
dev.off()

## The performance of the TMM normalization procedure can be examined using mean-difference
## (MD) plots. This visualizes the library size-adjusted log-fold change between two libraries
## (the difference) against the average log-expression across those libraries (the mean). 
## The following MD plot is generated by comparing sample 1 against an artificial library constructed
## from the average of all other samples. Ideally, the bulk of genes should be centred at a log-fold change of zero. 
## This indicates that any composition bias between libraries has been successfully removed. This quality check
## should be repeated by constructing a MD plot for each sample (column=X, where X is one of each columns in "cpm(dgList, log=TRUE)").
pdf(file="per_lib_meanDiff_plots.pdf")
par(mfrow=c(n2mfrow(length(colnames(dgList)))))
for (i in c(1:length(colnames(dgList)))) {
	plotMD(cpm(dgList, log=T, prior.count=2), column=i) 
	abline(h=0, col="red", lty=2, lwd=2)
}
dev.off()

## Removal of zero (CPM) count samples and normalization using different methods 
## Filter genes with raw counts < 1, following Li et al (2017), 10.1371/journal.pone.0176185... Note however that these are non-CPM counts, and perhaps this leads to many false DE
# keep <- rowMeans(dgList$counts) >= 1
# keep <- rowSums(cpm(dgList, log=F, prior.count=2)) >= length(colnames(dgList$counts)) 
keep <- rowMeans(cpm(dgList, log=F, prior.count=2)) >= 1 
dgList_NormTMM <- DGEList(dgList$counts[keep, ], group=Group, lib.size= colSums(dgList$counts[keep, ]))
dgList_NormTMM <- calcNormFactors(dgList_NormTMM, method="TMM") ## Trimmed Mean M-values

#dgList_NormRLE <- DGEList(dgList$counts[keep, ], group=Group, lib.size= colSums(dgList$counts[keep, ]))
#dgList_NormRLE <- calcNormFactors(dgList_NormRLE, method="RLE") ## Relative log expression
#dgList_NormUpQuart <- DGEList(dgList$counts[keep, ], group=Group, lib.size= colSums(dgList$counts[keep, ]))
#dgList_NormUpQuart <- calcNormFactors(dgList_NormUpQuart, method="upperquartile") ## Upper-quartile normalization
#dgList_QuantNormVoom <- DGEList(dgList$counts[keep, ], group=Group, lib.size= colSums(dgList$counts[keep, ]))
#dgList_QuantNormVoom <- voom(dgList_QuantNormVoom, normalize.method="quantile", save.plot=T, design=design) ## Quantile normalization-Voom

## Plot of log2 count density after normalization methods and removal of zero-count samples
pdf(file="density_log2CPM_NormTMM.pdf")
# sampleColors=c("blue", "blue", "deepskyblue", "blue", "deepskyblue", "blue", "deepskyblue", "blue", "green", "red", "pink", "red", "pink", "pink", "red", "red", "pink")
sampleColors=c("blue", "blue", "deepskyblue", "blue", "deepskyblue", "blue", "deepskyblue", "blue", "red", "pink", "red", "pink", "pink", "red", "red", "pink") ## IN CASE I29365 WAS REMOVED
plot(density(cpm(dgList_NormTMM[,1], log=T, prior.count=2)), col=sampleColors[1], lwd=2, ylim=c(0,0.3), xlab="log2CPM + 2", main="After TMM normalization")
for(i in 2:length(colnames(dgList$counts))) { 
	lines(density(cpm(dgList_NormTMM[,i], log=T, prior.count=2)), col=sampleColors[i], lwd=2)
}
dev.off()

## Mean-difference (MD) plots after normalization
pdf(file="per_lib_meanDiff_NormTMM_plots.pdf")
par(mfrow=c(n2mfrow(length(colnames(dgList_NormTMM)))))
for (i in c(1:length(colnames(dgList_NormTMM)))) {
	plotMD(cpm(dgList_NormTMM, log=T, prior.count=2), column=i)
	abline(h=0, col="red", lty=2, lwd=2)
}
dev.off()

## Data Exploration with ordination
pdf(file="MDS_expr_profiles.pdf")
points <- c(15,15,15,15)
colors <- c("blue", "deepskyblue", "red", "pink")
ordin_plot <- plotMDS(dgList_NormTMM, plot=F)
plot(ordin_plot, col=colors[Group], pch=points[Group], xlab="Leading logFC dim 1", ylab="Leading logFC dim 2", main="Multi-Dim plot TMM-Norm expression profiles")
text(ordin_plot$cmdscale.out, labels=colnames(dgList_NormTMM), col=colors[Group], pos=1)
legend("topright", legend=levels(Group), pch=points, col=colors, ncol=2)
dev.off()

## Update model for variable adjustment
designNew <- model.matrix(~ 0 
# + situation
# + sex
+ Group 
)

## Estimating the dispersion (Biological coefficent of variation)
dgList_NormDispers <- estimateDisp(dgList_NormTMM, designNew, mixed.df=F, robust=T)

## Plot dispersions (Biological coefficent of variation)
pdf(file="BCV_disperssion_genewise.pdf")
plotBCV(dgList_NormDispers, main="Biological Coefficient of Variation", col.common="gray50", col.trend="gray")
dev.off()

## Fit negative binomial Generalized linear model 
fit <- glmFit(dgList_NormDispers, designNew)

## Fit models sing Quasi-Likelihood method instead of classical linear models
# fit <- glmQLFit(dgList_NormDispers, designNew)

## Contrast Sym vs Allo within MALES
MALES_SymVsAllo.contrasts <- makeContrasts(
	AllovsSym.M = GroupAllo.M - GroupSym.M, 
	levels=designNew)
lrt_MALES_SymVsAllo.contrasts <- glmLRT(fit, contrast=MALES_SymVsAllo.contrasts)
# lrt_MALES_SymVsAllo.contrasts <- glmQLFTest(fit, contrast=MALES_SymVsAllo.contrasts)
topTags_MALES_SymVsAllo.contrasts <- topTags(lrt_MALES_SymVsAllo.contrasts, n=500, p.value=0.05, sort.by="PValue")
LRTvalues_MALES_SymVsAllo.contrasts <- lrt_MALES_SymVsAllo.contrasts$table
write.table(topTags_MALES_SymVsAllo.contrasts, "topTags_MALES_SymVsAllo.txt", sep="\t", quote=F)
write.table(LRTvalues_MALES_SymVsAllo.contrasts, "LRT_MALES_SymVsAllo.txt", sep="\t", quote=F)

pdf(file="MALES_SymVsAllo_contrasts_MeanDiff.pdf")
plotMD(lrt_MALES_SymVsAllo.contrasts, main="LRT MALES: Sym vs. Allo")
dev.off()

## Contrast Sym vs Allo within FEMALES
FEMALES_SymVsAllo.contrasts <- makeContrasts(
	AllovsSym.F = GroupAllo.F - GroupSym.F, 
levels=designNew)
lrt_FEMALES_SymVsAllo.contrasts <- glmLRT(fit, contrast=FEMALES_SymVsAllo.contrasts)
# lrt_FEMALES_SymVsAllo.contrasts <- glmQLFTest(fit, contrast=FEMALES_SymVsAllo.contrasts)
topTags_FEMALES_SymVsAllo.contrasts <- topTags(lrt_FEMALES_SymVsAllo.contrasts, n=500, p.value=0.05, sort.by="PValue")
LRTvalues_FEMALES_SymVsAllo.contrasts <- lrt_FEMALES_SymVsAllo.contrasts$table
write.table(topTags_FEMALES_SymVsAllo.contrasts, "topTags_FEMALES_SymVsAllo.txt", sep="\t", quote=F)
write.table(LRTvalues_FEMALES_SymVsAllo.contrasts, "LRT_FEMALES_SymVsAllo.txt", sep="\t", quote=F)

pdf(file="FEMALES_SymVsAllo_contrasts_MeanDiff.pdf")
plotMD(lrt_FEMALES_SymVsAllo.contrasts, main="LRT FEMALES: Sym vs. Allo")
dev.off()

## Contrast F vs M within SYMPATRY
SYMPATRY_FVsM.contrasts <- makeContrasts(
	Sym.FvsM = GroupSym.F - GroupSym.M, 
	levels=designNew)
lrt_SYMPATRY_FVsM.contrasts <- glmLRT(fit, contrast=SYMPATRY_FVsM.contrasts)
# lrt_SYMPATRY_FVsM.contrasts <- glmQLFTest(fit, contrast=SYMPATRY_FVsM.contrasts)
topTags_SYMPATRY_FVsM.contrasts <- topTags(lrt_SYMPATRY_FVsM.contrasts, n=500, p.value=0.05, sort.by="PValue")
LRTvalues_SYMPATRY_FVsM.contrasts  <- lrt_SYMPATRY_FVsM.contrasts$table
write.table(topTags_SYMPATRY_FVsM.contrasts, "topTags_SYMPATRY_FVsM.txt", sep="\t", quote=F)
write.table(LRTvalues_SYMPATRY_FVsM.contrasts, "LRT_SYMPATRY_FVsM.txt", sep="\t", quote=F)

pdf(file="SYMPATRY_FVsM_contrasts_MeanDiff.pdf")
plotMD(lrt_SYMPATRY_FVsM.contrasts, main="LRT SYMPATRY: F vs. M")
dev.off()

## Contrast F vs M within ALLOPATRY
ALLOPATRY_FVsM.contrasts <- makeContrasts(
	Allo.FvsM = GroupAllo.F - GroupAllo.M, 
levels=designNew)
lrt_ALLOPATRY_FVsM.contrasts <- glmLRT(fit, contrast=ALLOPATRY_FVsM.contrasts)
# lrt_ALLOPATRY_FVsM.contrasts <- glmQLFTest(fit, contrast=ALLOPATRY_FVsM.contrasts)
topTags_ALLOPATRY_FVsM.contrasts <- topTags(lrt_ALLOPATRY_FVsM.contrasts, n=500, p.value=0.05, sort.by="PValue")
LRTvalues_ALLOPATRY_FVsM.contrasts <- lrt_ALLOPATRY_FVsM.contrasts$table
write.table(topTags_ALLOPATRY_FVsM.contrasts, "topTags_ALLOPATRY_FVsM.txt", sep="\t", quote=F)
write.table(LRTvalues_ALLOPATRY_FVsM.contrasts, "LRT_ALLOPATRY_FVsM.txt", sep="\t", quote=F)

pdf(file="ALLOPATRY_FVsM_contrasts_MeanDiff.pdf")
plotMD(lrt_ALLOPATRY_FVsM.contrasts, main="LRT ALLOPATRY: F vs. M")
dev.off()


## HEATMAPS

mypalette <- brewer.pal(11,"PRGn")
morecols <- colorRampPalette(mypalette)

## Heatmap Sym vs Allo within MALES
DEcontigs_MALES_SymVsAllo <- rownames(topTags_MALES_SymVsAllo.contrasts$table)
DE_cpm_MALES_SymVsAllo <- dgList_NormDispers$counts[is.element(rownames(dgList_NormDispers$counts), DEcontigs_MALES_SymVsAllo),]
logcpm_MALES_SymVsAllo <- cpm(DE_cpm_MALES_SymVsAllo, prior.count=2, log=TRUE)
z_logcpm_MALES_SymVsAllo <- t(scale(t(logcpm_MALES_SymVsAllo), scale=T, center=T))
z_logcpm_MALES_SymVsAllo <- merge(z_logcpm_MALES_SymVsAllo, topTags_MALES_SymVsAllo.contrasts$table, by=0)
z_logcpm_MALES_SymVsAllo <- z_logcpm_MALES_SymVsAllo[order(z_logcpm_MALES_SymVsAllo$logFC), ]
z_logcpm_MALES_SymVsAllo <- z_logcpm_MALES_SymVsAllo[,-c(18:22)]
rownames(z_logcpm_MALES_SymVsAllo) <- z_logcpm_MALES_SymVsAllo$Row.names
z_logcpm_MALES_SymVsAllo <- z_logcpm_MALES_SymVsAllo[,-1]
z_logcpm_MALES_SymVsAllo <- as.matrix(z_logcpm_MALES_SymVsAllo)
ColType <- NULL
for(i in colnames(z_logcpm_MALES_SymVsAllo)) {
	ColType <- append(ColType, as.vector(sampleMeta[grep(i, rownames(sampleMeta)), 13]))
}
pdf(file="MALES_SymVsAllo_PVClust.pdf")
# genesPV <- pvclust(t(z_logcpm_MALES_SymVsAllo), nboot=100)
feriarumPV_MALES_SymVsAllo <- pvclust(z_logcpm_MALES_SymVsAllo, nboot=100)
feriarumPV_MALES_SymVsAllo$hclust <- rotate(feriarumPV_MALES_SymVsAllo$hclust, 
c("I29359", "I29361", "I29363", "I29367", "I29369", "I29370", "I29373", "I29357", "I29358", "I29360", "I29362", "I29364", "I29366", "I29368", "I29371", "I29372"))
plot(feriarumPV_MALES_SymVsAllo)
dev.off()
hAnnot <- HeatmapAnnotation(type=ColType, show_legend=F, col = list(type = c("Allo.F"="blue", "Allo.M"="deepskyblue", "Sym.F"="red", "Sym.M"="pink")))
pdf(file="MALES_SymVsAllo_heatmap.pdf", height=15, width=10)
Heatmap(z_logcpm_MALES_SymVsAllo, cluster_columns = feriarumPV_MALES_SymVsAllo$hclust, heatmap_legend_param = list(title = "feriarum"), bottom_annotation=hAnnot, 
col=rev(mypalette), 
# cluster_rows=genesPV$hclust, 
cluster_rows=F, clustering_distance_rows="euclidean",
show_row_dend=F, row_dend_reorder=F)
dev.off()

## Heatmap Sym vs Allo within FEMALES
DEcontigs_FEMALES_SymVsAllo <- rownames(topTags_FEMALES_SymVsAllo.contrasts$table)
DE_cpm_FEMALES_SymVsAllo <- dgList_NormDispers$counts[is.element(rownames(dgList_NormDispers$counts), DEcontigs_FEMALES_SymVsAllo),]
logcpm_FEMALES_SymVsAllo <- cpm(DE_cpm_FEMALES_SymVsAllo, prior.count=2, log=TRUE)
z_logcpm_FEMALES_SymVsAllo <- t(scale(t(logcpm_FEMALES_SymVsAllo), scale=T, center=T))
z_logcpm_FEMALES_SymVsAllo <- merge(z_logcpm_FEMALES_SymVsAllo, topTags_FEMALES_SymVsAllo.contrasts$table, by=0)
z_logcpm_FEMALES_SymVsAllo <- z_logcpm_FEMALES_SymVsAllo[order(z_logcpm_FEMALES_SymVsAllo$logFC), ]
z_logcpm_FEMALES_SymVsAllo <- z_logcpm_FEMALES_SymVsAllo[,-c(18:22)]
rownames(z_logcpm_FEMALES_SymVsAllo) <- z_logcpm_FEMALES_SymVsAllo$Row.names
z_logcpm_FEMALES_SymVsAllo <- z_logcpm_FEMALES_SymVsAllo[,-1]
z_logcpm_FEMALES_SymVsAllo <- as.matrix(z_logcpm_FEMALES_SymVsAllo)
ColType <- NULL
for(i in colnames(z_logcpm_FEMALES_SymVsAllo)) {
	ColType <- append(ColType, as.vector(sampleMeta[grep(i, rownames(sampleMeta)), 13]))
}

pdf(file="FEMALES_SymVsAllo_PVClust.pdf")
# genesPV <- pvclust(t(z_logcpm_FEMALES_SymVsAllo), nboot=100)
feriarumPV_FEMALES_SymVsAllo <- pvclust(z_logcpm_FEMALES_SymVsAllo, nboot=100)
feriarumPV_FEMALES_SymVsAllo$hclust <- rotate(feriarumPV_FEMALES_SymVsAllo$hclust, 
c("I29362", "I29359", "I29361", "I29363", "I29367", "I29369", "I29370", "I29373", "I29357", "I29358", "I29360", "I29364", "I29366", "I29368", "I29371", "I29372"))
plot(feriarumPV_FEMALES_SymVsAllo)
dev.off()
hAnnot <- HeatmapAnnotation(type=ColType, show_legend=F, col = list(type = c("Allo.F"="blue", "Allo.M"="deepskyblue", "Sym.F"="red", "Sym.M"="pink")))
pdf(file="FEMALES_SymVsAllo_heatmap.pdf", height=30, width=10)
Heatmap(z_logcpm_FEMALES_SymVsAllo, cluster_columns = feriarumPV_FEMALES_SymVsAllo$hclust, heatmap_legend_param = list(title = "feriarum"), bottom_annotation=hAnnot, 
col=rev(mypalette), 
# cluster_rows=genesPV$hclust, 
cluster_rows=F, clustering_distance_rows="euclidean",
show_row_dend=F, row_dend_reorder=F)
dev.off()

## Heatmap F vs M within SYMPATYRY
DEcontigs_SYMPATRY_FVsM <- rownames(topTags_SYMPATRY_FVsM.contrasts$table)
DE_cpm_SYMPATRY_FVsM <- dgList_NormDispers$counts[is.element(rownames(dgList_NormDispers$counts), DEcontigs_SYMPATRY_FVsM),]
logcpm_SYMPATRY_FVsM <- cpm(DE_cpm_SYMPATRY_FVsM, prior.count=2, log=TRUE)
z_logcpm_SYMPATRY_FVsM  <- t(scale(t(logcpm_SYMPATRY_FVsM), scale=T, center=T))
z_logcpm_SYMPATRY_FVsM <- merge(z_logcpm_SYMPATRY_FVsM, topTags_SYMPATRY_FVsM.contrasts$table, by=0)
z_logcpm_SYMPATRY_FVsM <- z_logcpm_SYMPATRY_FVsM[order(z_logcpm_SYMPATRY_FVsM$logFC), ]
z_logcpm_SYMPATRY_FVsM <- z_logcpm_SYMPATRY_FVsM[,-c(18:22)]
rownames(z_logcpm_SYMPATRY_FVsM) <- z_logcpm_SYMPATRY_FVsM$Row.names
z_logcpm_SYMPATRY_FVsM <- z_logcpm_SYMPATRY_FVsM[,-1]
z_logcpm_SYMPATRY_FVsM <- as.matrix(z_logcpm_SYMPATRY_FVsM)
ColType <- NULL
for(i in colnames(z_logcpm_SYMPATRY_FVsM)) {
	ColType <- append(ColType, as.vector(sampleMeta[grep(i, rownames(sampleMeta)), 13]))
}

pdf(file="SYMPATRY_FVsM_PVClust.pdf")
# genesPV <- pvclust(t(z_logcpm_SYMPATRY_FVsM), nboot=100)
feriarumPV_SYMPATRY_FVsM <- pvclust(z_logcpm_SYMPATRY_FVsM, nboot=100)
feriarumPV_SYMPATRY_FVsM$hclust <- rotate(feriarumPV_SYMPATRY_FVsM$hclust, 
c("I29359", "I29363", "I29367", "I29369", "I29370", "I29373", "I29361", "I29357", "I29358", "I29360", "I29362", "I29364",  "I29366", "I29368", "I29371", "I29372"))
plot(feriarumPV_SYMPATRY_FVsM)
dev.off()
hAnnot <- HeatmapAnnotation(type=ColType, show_legend=F, col = list(type = c("Allo.F"="blue", "Allo.M"="deepskyblue", "Sym.F"="red", "Sym.M"="pink")))
pdf(file="SYMPATRY_FVsM_heatmap.pdf", height=20, width=10)
Heatmap(z_logcpm_SYMPATRY_FVsM, cluster_columns = feriarumPV_SYMPATRY_FVsM$hclust, heatmap_legend_param = list(title = "feriarum"), bottom_annotation=hAnnot, 
col=rev(mypalette),
# cluster_rows=genesPV$hclust, 
cluster_rows=T, clustering_distance_rows="euclidean",
show_row_dend=F, row_dend_reorder=T)
dev.off()

## Heatmap F vs M within ALLOPATYRY
DEcontigs_ALLOPATRY_FVsM <- rownames(topTags_ALLOPATRY_FVsM.contrasts$table)
DE_cpm_ALLOPATRY_FVsM <- dgList_NormDispers$counts[is.element(rownames(dgList_NormDispers$counts), DEcontigs_ALLOPATRY_FVsM),]
logcpm_ALLOPATRY_FVsM<- cpm(DE_cpm_ALLOPATRY_FVsM, prior.count=2, log=TRUE)
z_logcpm_ALLOPATRY_FVsM   <- t(scale(t(logcpm_ALLOPATRY_FVsM), scale=T, center=T))
z_logcpm_ALLOPATRY_FVsM <- merge(z_logcpm_ALLOPATRY_FVsM, topTags_ALLOPATRY_FVsM.contrasts$table, by=0)
z_logcpm_ALLOPATRY_FVsM <- z_logcpm_ALLOPATRY_FVsM[order(z_logcpm_ALLOPATRY_FVsM$logFC), ]
z_logcpm_ALLOPATRY_FVsM <- z_logcpm_ALLOPATRY_FVsM[,-c(18:22)]
rownames(z_logcpm_ALLOPATRY_FVsM) <- z_logcpm_ALLOPATRY_FVsM$Row.names
z_logcpm_ALLOPATRY_FVsM <- z_logcpm_ALLOPATRY_FVsM[,-1]
z_logcpm_ALLOPATRY_FVsM <- as.matrix(z_logcpm_ALLOPATRY_FVsM)
ColType <- NULL
for(i in colnames(z_logcpm_ALLOPATRY_FVsM)) {
	ColType <- append(ColType, as.vector(sampleMeta[grep(i, rownames(sampleMeta)), 13]))
}

pdf(file="ALLOPATRY_FVsM_PVClust.pdf")
# genesPV <- pvclust(t(z_logcpm_ALLOPATRY_FVsM), nboot=100)
feriarumPV_ALLOPATRY_FVsM <- pvclust(z_logcpm_ALLOPATRY_FVsM, nboot=100)
feriarumPV_ALLOPATRY_FVsM$hclust <- rotate(feriarumPV_ALLOPATRY_FVsM$hclust, 
c("I29359", "I29361", "I29363", "I29367", "I29369", "I29370", "I29373", "I29366", "I29372", "I29368", "I29371", "I29357", "I29358", "I29360", "I29362", "I29364"))
plot(feriarumPV_ALLOPATRY_FVsM)
dev.off()
hAnnot <- HeatmapAnnotation(type=ColType, show_legend=F, col = list(type = c("Allo.F"="blue", "Allo.M"="deepskyblue", "Sym.F"="red", "Sym.M"="pink")))
pdf(file="ALLOPATRY_FVsM_heatmap.pdf", height=20, width=10)
Heatmap(z_logcpm_ALLOPATRY_FVsM, cluster_columns = feriarumPV_ALLOPATRY_FVsM$hclust, heatmap_legend_param = list(title = "feriarum"), bottom_annotation=hAnnot, 
col=rev(mypalette), 
# cluster_rows=genesPV$hclust, 
cluster_rows=T, clustering_distance_rows="euclidean",
show_row_dend=F, row_dend_reorder=T)
dev.off()


## HEATMAPS w/GENE ANNOTATIONS
deGenesfpath <- "~/Desktop/AlanCounts_DEGenes_ALL.txt"
annotsfpath <- "~/Desktop/Trinotate_Genes_FirstAnnot_wSYMBOLS.txt"
annots <- read.csv(annotsfpath)
deGenes <- read.csv(deGenesfpath)
deGenes <- as.vector(deGenes[[1]])

## Heatmap Sym vs Allo within MALES w/GENE ANNOTATIONS
annotsHmap <- rownames(z_logcpm_MALES_SymVsAllo) %in% annots[[1]] ## Finds TOM genes in the list of DE genes
annotAlt <- c()
for(i in 1:length(annotsHmap)) {
	idTemp <- as.vector(rownames(z_logcpm_MALES_SymVsAllo)[i])
	if(annotsHmap[i] == "TRUE") {
		symbolTemp <- annots[grep(idTemp, as.vector(annots[[1]])), 2]
		annotAlt[i] <- as.vector(symbolTemp)
	}
	else {
		annotAlt[i] <- idTemp
	}
}
hAnnot <- HeatmapAnnotation(type=ColType, show_legend=F, col = list(type = c("Allo.F"="blue", "Allo.M"="deepskyblue", "Sym.F"="red", "Sym.M"="pink")))
z_logcpm_MALES_SymVsAllo_Annots <- z_logcpm_MALES_SymVsAllo
rownames(z_logcpm_MALES_SymVsAllo_Annots) <- annotAlt 
pdf(file="MALES_SymVsAllo_heatmap_wAnnots.pdf", height=15, width=10)
Heatmap(z_logcpm_MALES_SymVsAllo_Annots, cluster_columns = feriarumPV_MALES_SymVsAllo$hclust, heatmap_legend_param = list(title = "feriarum"), bottom_annotation=hAnnot, 
col=rev(mypalette), 
# cluster_rows=genesPV$hclust, 
cluster_rows=F, clustering_distance_rows="euclidean",
show_row_dend=F, row_dend_reorder=F)
dev.off()

## Heatmap Sym vs Allo within FEMALES w/GENE ANNOTATIONS
annotsHmap <- rownames(z_logcpm_FEMALES_SymVsAllo) %in% annots[[1]] ## Finds TOM genes in the list of DE genes
annotAlt <- c()
for(i in 1:length(annotsHmap)) {
	idTemp <- as.vector(rownames(z_logcpm_FEMALES_SymVsAllo)[i])
	if(annotsHmap[i] == "TRUE") {
		symbolTemp <- annots[grep(idTemp, as.vector(annots[[1]])), 2]
		annotAlt[i] <- as.vector(symbolTemp)
	}
	else {
		annotAlt[i] <- idTemp
	}
}
hAnnot <- HeatmapAnnotation(type=ColType, show_legend=F, col = list(type = c("Allo.F"="blue", "Allo.M"="deepskyblue", "Sym.F"="red", "Sym.M"="pink")))
z_logcpm_FEMALES_SymVsAllo_Annots <- z_logcpm_FEMALES_SymVsAllo
rownames(z_logcpm_FEMALES_SymVsAllo_Annots) <- annotAlt
pdf(file="FEMALES_SymVsAllo_heatmap_wAnnots.pdf", height=30, width=10)
Heatmap(z_logcpm_FEMALES_SymVsAllo_Annots, cluster_columns = feriarumPV_FEMALES_SymVsAllo$hclust, heatmap_legend_param = list(title = "feriarum"), bottom_annotation=hAnnot, 
col=rev(mypalette), 
# cluster_rows=genesPV$hclust, 
cluster_rows=F, clustering_distance_rows="euclidean",
show_row_dend=F, row_dend_reorder=F)
dev.off()

## Heatmap F vs M within SYMPATYRY w/GENE ANNOTATIONS
annotsHmap <- rownames(z_logcpm_SYMPATRY_FVsM) %in% annots[[1]] ## Finds TOM genes in the list of DE genes
annotAlt <- c()
for(i in 1:length(annotsHmap)) {
	idTemp <- as.vector(rownames(z_logcpm_SYMPATRY_FVsM)[i])
	if(annotsHmap[i] == "TRUE") {
		symbolTemp <- annots[grep(idTemp, as.vector(annots[[1]])), 2]
		annotAlt[i] <- as.vector(symbolTemp)
	}
	else {
		annotAlt[i] <- idTemp
	}
}
hAnnot <- HeatmapAnnotation(type=ColType, show_legend=F, col = list(type = c("Allo.F"="blue", "Allo.M"="deepskyblue", "Sym.F"="red", "Sym.M"="pink")))
z_logcpm_SYMPATRY_FVsM_Annots <- z_logcpm_SYMPATRY_FVsM
rownames(z_logcpm_SYMPATRY_FVsM_Annots) <- annotAlt
pdf(file="SYMPATRY_FVsM_heatmap_wAnnots.pdf", height=20, width=10)
Heatmap(z_logcpm_SYMPATRY_FVsM_Annots, cluster_columns = feriarumPV_SYMPATRY_FVsM$hclust, heatmap_legend_param = list(title = "feriarum"), bottom_annotation=hAnnot, 
col=rev(mypalette),
# cluster_rows=genesPV$hclust, 
cluster_rows=T, clustering_distance_rows="euclidean",
show_row_dend=F, row_dend_reorder=T)
dev.off()

## Heatmap F vs M within ALLOPATYRY w/GENE ANNOTATIONS
annotsHmap <- rownames(z_logcpm_ALLOPATRY_FVsM) %in% annots[[1]] ## Finds TOM genes in the list of DE genes
annotAlt <- c()
for(i in 1:length(annotsHmap)) {
	idTemp <- as.vector(rownames(z_logcpm_ALLOPATRY_FVsM)[i])
	if(annotsHmap[i] == "TRUE") {
		symbolTemp <- annots[grep(idTemp, as.vector(annots[[1]])), 2]
		annotAlt[i] <- as.vector(symbolTemp)
	}
	else {
		annotAlt[i] <- idTemp
	}
}
hAnnot <- HeatmapAnnotation(type=ColType, show_legend=F, col = list(type = c("Allo.F"="blue", "Allo.M"="deepskyblue", "Sym.F"="red", "Sym.M"="pink")))
z_logcpm_ALLOPATRY_FVsM_Annots <- z_logcpm_ALLOPATRY_FVsM
rownames(z_logcpm_ALLOPATRY_FVsM_Annots) <- annotAlt
pdf(file="ALLOPATRY_FVsM_heatmap_wAnnots.pdf", height=20, width=10)
Heatmap(z_logcpm_ALLOPATRY_FVsM_Annots, cluster_columns = feriarumPV_ALLOPATRY_FVsM$hclust, heatmap_legend_param = list(title = "feriarum"), bottom_annotation=hAnnot, 
col=rev(mypalette), 
# cluster_rows=genesPV$hclust, 
cluster_rows=T, clustering_distance_rows="euclidean",
show_row_dend=F, row_dend_reorder=T)
dev.off()


## VOLCANO PLOTS
topTags_ANNOTS <- read.csv("../AlanCounts_DEGenes_ALL_AnnotSYMBOLS.csv")
colnames(topTags_ANNOTS) <- c("contig", "sprotsymbol")

## Volcano Plot Sym vs Allo within MALES
pdf(file="MALES_SymVsAllo_VolcanoPlot.pdf")
plot(LRTvalues_MALES_SymVsAllo.contrasts[!is.element(rownames(LRTvalues_MALES_SymVsAllo.contrasts), DEcontigs_MALES_SymVsAllo), ]$logFC, 
-log10(LRTvalues_MALES_SymVsAllo.contrasts[!is.element(rownames(LRTvalues_MALES_SymVsAllo.contrasts), DEcontigs_MALES_SymVsAllo), ]$PValue), 
ylim=c(0, max(-log10(LRTvalues_MALES_SymVsAllo.contrasts$PValue))), xlim=c(min(LRTvalues_MALES_SymVsAllo.contrasts$logFC), max(LRTvalues_MALES_SymVsAllo.contrasts$logFC)),
pch=20, ylab="log10PValue", xlab="log2FC (Sym vs Allo)", main="DE genes Sym vs Allo (MALES)")
with(subset(topTags_MALES_SymVsAllo.contrasts$table, logFC < 0), points(logFC, -log10(PValue), col="red", pch=20))
with(subset(topTags_MALES_SymVsAllo.contrasts$table, logFC > 0), points(logFC, -log10(PValue), col="blue", pch=20))
for(i in rownames(topTags_MALES_SymVsAllo.contrasts$table)) {
	tagsymbol <- as.vector(topTags_ANNOTS$sprotsymbol[grep(i, topTags_ANNOTS$contig)][1])
	text(topTags_MALES_SymVsAllo.contrasts$table$logFC[rownames(topTags_MALES_SymVsAllo.contrasts$table)==i], 
	-log10(topTags_MALES_SymVsAllo.contrasts$table$PValue[rownames(topTags_MALES_SymVsAllo.contrasts$table)==i]),
	labels=tagsymbol, cex=0.5, col="black", pch=20, pos=2)
}
dev.off()

## Volcano Plot Sym vs Allo within FEMALES
pdf(file="FEMALES_SymVsAllo_VolcanoPlot.pdf")
plot(LRTvalues_FEMALES_SymVsAllo.contrasts[!is.element(rownames(LRTvalues_FEMALES_SymVsAllo.contrasts), DEcontigs_FEMALES_SymVsAllo), ]$logFC, 
-log10(LRTvalues_FEMALES_SymVsAllo.contrasts[!is.element(rownames(LRTvalues_FEMALES_SymVsAllo.contrasts), DEcontigs_FEMALES_SymVsAllo), ]$PValue), 
ylim=c(0, max(-log10(LRTvalues_FEMALES_SymVsAllo.contrasts$PValue))), xlim=c(min(LRTvalues_FEMALES_SymVsAllo.contrasts$logFC), max(LRTvalues_FEMALES_SymVsAllo.contrasts$logFC)),
pch=20, ylab="log10PValue", xlab="log2FC (Sym vs Allo)", main="DE genes Sym vs Allo (FEMALES)")
with(subset(topTags_FEMALES_SymVsAllo.contrasts$table, logFC < 0), points(logFC, -log10(PValue), col="red", pch=20))
with(subset(topTags_FEMALES_SymVsAllo.contrasts$table, logFC > 0), points(logFC, -log10(PValue), col="blue", pch=20))
for(i in rownames(topTags_FEMALES_SymVsAllo.contrasts$table)) {
	tagsymbol <- as.vector(topTags_ANNOTS$sprotsymbol[grep(i, topTags_ANNOTS$contig)][1])
	text(topTags_FEMALES_SymVsAllo.contrasts$table$logFC[rownames(topTags_FEMALES_SymVsAllo.contrasts$table)==i], 
	-log10(topTags_FEMALES_SymVsAllo.contrasts$table$PValue[rownames(topTags_FEMALES_SymVsAllo.contrasts$table)==i]),
	labels=tagsymbol, cex=0.5, col="black", pch=20, pos=2)
}
dev.off()

## Volcano Plot F vs M within SYMPATYRY
pdf(file="SYMPATRY_FVsM_VolcanoPlot.pdf")
plot(LRTvalues_SYMPATRY_FVsM.contrasts[!is.element(rownames(LRTvalues_SYMPATRY_FVsM.contrasts), DEcontigs_SYMPATRY_FVsM), ]$logFC, 
-log10(LRTvalues_SYMPATRY_FVsM.contrasts[!is.element(rownames(LRTvalues_SYMPATRY_FVsM.contrasts), DEcontigs_SYMPATRY_FVsM), ]$PValue), 
ylim=c(0, max(-log10(LRTvalues_SYMPATRY_FVsM.contrasts$PValue))), xlim=c(min(LRTvalues_SYMPATRY_FVsM.contrasts$logFC), max(LRTvalues_SYMPATRY_FVsM.contrasts$logFC)),
pch=20, ylab="log10PValue", xlab="log2FC (F vs M)", main="DE genes F vs M (SYMPATRY)")
with(subset(topTags_SYMPATRY_FVsM.contrasts$table, logFC < 0), points(logFC, -log10(PValue), col="red", pch=20))
with(subset(topTags_SYMPATRY_FVsM.contrasts$table, logFC > 0), points(logFC, -log10(PValue), col="blue", pch=20))
for(i in rownames(topTags_SYMPATRY_FVsM.contrasts$table)) {
	tagsymbol <- as.vector(topTags_ANNOTS$sprotsymbol[grep(i, topTags_ANNOTS$contig)][1])
	text(topTags_SYMPATRY_FVsM.contrasts$table$logFC[rownames(topTags_SYMPATRY_FVsM.contrasts$table)==i], 
	-log10(topTags_SYMPATRY_FVsM.contrasts$table$PValue[rownames(topTags_SYMPATRY_FVsM.contrasts$table)==i]),
	labels=tagsymbol, cex=0.5, col="black", pch=20, pos=2)
}
dev.off()

## Volcano Plot F vs M within ALLOPATYRY
pdf(file="ALLOPATRY_FVsM_VolcanoPlot.pdf")
plot(LRTvalues_ALLOPATRY_FVsM.contrasts[!is.element(rownames(LRTvalues_ALLOPATRY_FVsM.contrasts), DEcontigs_ALLOPATRY_FVsM), ]$logFC, 
-log10(LRTvalues_ALLOPATRY_FVsM.contrasts[!is.element(rownames(LRTvalues_ALLOPATRY_FVsM.contrasts), DEcontigs_ALLOPATRY_FVsM), ]$PValue), 
ylim=c(0, max(-log10(LRTvalues_ALLOPATRY_FVsM.contrasts$PValue))), xlim=c(min(LRTvalues_ALLOPATRY_FVsM.contrasts$logFC), max(LRTvalues_ALLOPATRY_FVsM.contrasts$logFC)),
pch=20, ylab="log10PValue", xlab="log2FC (F vs M)", main="DE genes F vs M (ALLOPATRY)")
with(subset(topTags_ALLOPATRY_FVsM.contrasts$table, logFC < 0), points(logFC, -log10(PValue), col="red", pch=20))
with(subset(topTags_ALLOPATRY_FVsM.contrasts$table, logFC > 0), points(logFC, -log10(PValue), col="blue", pch=20))
for(i in rownames(topTags_ALLOPATRY_FVsM.contrasts$table)) {
	tagsymbol <- as.vector(topTags_ANNOTS$sprotsymbol[grep(i, topTags_ANNOTS$contig)][1])
	text(topTags_ALLOPATRY_FVsM.contrasts$table$logFC[rownames(topTags_ALLOPATRY_FVsM.contrasts$table)==i], 
	-log10(topTags_ALLOPATRY_FVsM.contrasts$table$PValue[rownames(topTags_ALLOPATRY_FVsM.contrasts$table)==i]),
	labels=tagsymbol, cex=0.5, col="black", pch=20, pos=2)
}
dev.off()


## ORDINATION based on DE genes
tTags_ALLDFs <- grep("topTags", ls(), value=T)

tTagstmp <- get(tTags_ALLDFs[1])$table
for(i in 2:length(tTags_ALLDFs)) {
	tTagstmp <- rbind(tTagstmp, get(tTags_ALLDFs[i])$table)
}

AlltTags <- unique(rownames(tTagstmp))

dgList_NormTMM_AlltTags <- as.data.frame(dgList_NormTMM$counts)[AlltTags, ]
dgList_NormTMM_AlltTags <- na.omit(dgList_NormTMM_AlltTags)

pdf(file="MDS_log2expr_profiles_DEGenes.pdf")
points <- c(15,15,15,15)
colors <- c("blue", "deepskyblue", "red", "pink")
ordin_plot <- plotMDS(cpm(dgList_NormTMM_AlltTags, prior.count=2, log=T), plot=F)
plot(ordin_plot, col=colors[Group], pch=points[Group], xlab="Leading logFC dim 1", ylab="Leading logFC dim 2", main="Multi-Dim plot TMM-Norm expression profiles")
text(ordin_plot$cmdscale.out, labels=colnames(dgList_NormTMM), col=colors[Group], pos=1)
legend("topright", legend=levels(Group), pch=points, col=colors, ncol=2)
dev.off()


## Removing DE Genes from MDS to see effect
#setwd("~/Desktop/MDS_subsample_tTags")
#forCounter <- seq(1, length(rownames(dgList_NormTMM_AlltTags)), by=2)
#forCounter[length(forCounter)] <- length(rownames(dgList_NormTMM_AlltTags))
#j <- 1
#for(i in forCounter) {
#	j <- j+1
#	tmpFordgList <- cpm(dgList_NormTMM_AlltTags[-c(i:forCounter[j]), ], prior.count=2, log=T)
#	pdf(file=paste("MDS_expr_profiles_DEGenes_minus_", i, "-", forCounter[j], ".pdf", sep=""))
#	points <- c(15,15,15,15)
#	colors <- c("blue", "deepskyblue", "red", "pink")
#	ordin_plot <- plotMDS(tmpFordgList, plot=F)
#	plot(ordin_plot, col=colors[Group], pch=points[Group], xlab="Leading logFC dim 1", ylab="Leading logFC dim 2", main="Multi-Dim plot TMM-Norm expression profiles", xlim=c(-5, 5), ylim=c(-5, 5))
#	text(ordin_plot$cmdscale.out, labels=colnames(dgList_NormTMM), col=colors[Group], pos=1)
#	legend("topright", legend=levels(Group), pch=points, col=colors, ncol=2)
#	dev.off()
#}
